# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:  :year/:month/:day/:title/


# Setup
title:               Hibri Marzook
tagline:             'Musings on technology and systems thinking'
description:         'Helping teams build and deliver software sustainably. Opinions are my own'
url:                 'https://www.hibri.net'
baseurl:             'https://www.hibri.net'
future: true

#github
github:
  repo: https://www.github.com/hibri/hibri.github.io
  user: hibri
# About/contact
author:
  name:              Hibri Marzook
  url:               https://twitter.com/hibri
  email:             hibri@hibri.net
  twitter:           hibri
  mastodon:          https://techhub.social/@hibri
  linkedin:          https://www.linkedin.com/in/hibri/

# Custom vars
version:             1.0.0
#Gems
gems: [jekyll-paginate, jekyll-feed]
paginate: 5
paginate_path: "page:num"
google_analytics: UA-107711-1

plugins:
  - jekyll-feed
