# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://hibri.github.io
baseurl:             'https://hibri.github.io/poole/'
paginate:            5

# About/contact
author:
  name:              Hibri Marzook
  url:               https://twitter.com/hibri
  email:             hibri@hibri.net

# Custom vars
version:             1.0.0
