# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:  /:year/:month/:day/:title/


# Setup
title:               Hibri Marzook
tagline:             'Musings on technology and photography'
description:         'Consultant at <a href="http://contino.io">Contino</a>. Love APIs, agile, tdd, continuous delivery and dev ops. Opinions are my own'
url:                 'http://www.hibri.net'
baseurl:             'http://www.hibri.net'
paginate:            5
future: true

#github
github:
  repo: https://www.github.com/hibri/hibri.github.io
  user: hibri
# About/contact
author:
  name:              Hibri Marzook
  url:               https://twitter.com/hibri
  email:             hibri@hibri.net
  twitter:           hibri

# Custom vars
version:             1.0.0
#Gems
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
