# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Hibri Marzook
tagline:             'Musings on technology and photography'
description:         'Consultant at <a href="http://contino.io">Contino</a>. Love APIs, agile, tdd, continuous delivery and dev ops. Opinions are my own'
url:                 'https://hibri.github.io'
baseurl:             'https://hibri.github.io'
paginate:            5


# About/contact
author:
  name:              Hibri Marzook
  url:               https://twitter.com/hibri
  email:             hibri@hibri.net
  twitter:           '@hibri'

# Custom vars
version:             1.0.0
#Gems
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"